#!/bin/sh

cd ~

export _JAVA_AWT_WM_NONREPARENTING=1

export $GRIM_DEFAULT_DIR=~/Pictures

export EDITOR=vim

export terminal=wezterm
export web_browser=firefox
export file_manager=pcmanfm
export editor=emacs

exec Hyprland
