#!/bin/sh

cd ~

export _JAVA_AWT_WM_NONREPARENTING=1

export $GRIM_DEFAULT_DIR=~/Pictures

export EDITOR=vim

export terminal="foot -c $HOME/.config/foot/dracula.ini"
export web_browser=firefox
export file_manager=pcmanfm
export editor=emacs
export editor2=$terminal -e nvim

exec Hyprland
