#!/bin/sh

sudo pacman -S --noconfirm hyprland \
      	                   htop \
                           papirus-icon-theme \
                           waybar \
                           eza \
                           qt5-wayland \
                           swaybg \
                           blueberry \
                           mako \
                           swaync \
                           wdisplays-git \
                           wl-clipboard \
                           grim \
                           slurp \
                           bat-extras \
                           fish \
                           starship \
                           pcmanfm-gtk3 \
                           file-roller \
                           p7zip \
                           unrar \
                           zathura \
			   zathura-pdf-mupdf \
                           neovim \
                           gammastep \
                           lolcat \
                           otf-codenewroman-nerd \
                           ttf-ubuntu-nerd \
                           ttf-go-nerd \
                           ttf-jetbrains-mono-nerd \
                           noto-fonts-emoji \
                           pavucontrol \
                           qt5ct \
                           foot \
                           networkmanager \
                           gksu \
                           qutebrowser \
                           mpv \
                           polkit-gnome \
                           grimshot \
                           dracula-cursors-git \
                           light \
                           chafa \
                           ripgrep \
                           fzf \
                           hyprpicker-git \
                           swayimg \
                           emacs \
                           lf \
                           stow \
                           expac \
			   python-tldextract \
                           python-pynacl \
		           fastfetch
