#!/bin/sh

pgrep -x sxhkd > /dev/null

# variables for sxhkdrc
export terminal="alacritty"
export web_browser="firefox"
export file_manager="pcmanfm"
export editor="emacs"

export EDITOR="vim"

# hotkey daemon
sxhkd &

# script starting polybar
~/.config/scripts/polybar-start.sh

# script for gtk theming
~/.config/scripts/hypr/theme.sh

# wallpaper
#nitrogen --restore
variety &

# compositor
picom &

# notifications
dunst -config ~/.config/dunst/catppuccin-mocha.conf &

# drive mounting daemon
udiskie &

# you can add as many workspaces as you want
bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config focus_follows_pointer true
bspc config pointer_action1       move
bspc config pointer_action2       resize_side
bspc config pointer_action3       resize_corner
bspc config border_width          3
bspc config window_gap            7

bspc config split_ratio           0.0
bspc config borderless_monocle    true
bspc config gapless_monocle       true

bspc rule -a Screenkey manage=off

bspc rule -a Emacs  state=tiled
bspc rule -a Arandr state=floating
bspc rule -a sxiv   state=floating
