#+TITLE: Bspwm config
#+PROPERTY: header-args :tangle bspwmrc
#+auto_tangle: t

* Table of contents :toc:
- [[#bspwmrc][bspwmrc]]
- [[#code][code]]
  - [[#variables][variables]]
  - [[#essential-startups][essential startups]]
  - [[#bspc-rules][bspc rules]]

* bspwmrc
bspwrc is a shell script that gets read by bspwm on its startup.
You can load programs and settings with this.
The default path of bspwmrc is =$HOME/.config/bspwm/bspwmrc=.

* code

** variables
The first thing is setting my variables.
These will be used for [[../sxhkd/sxhkdrc][sxhkdrc]].

- =terminal= - default terminal emulator
- =web_browser= - default web browser
- =file_manager= - default file manager
- =editor= - default IDE
- =editor2= - 2nd IDE (neovim doesn't work properly so don't use it)
- =EDITOR= - default editor in terminal

#+BEGIN_SRC shell :shebang "#!/bin/bash"

# variables for sxhkdrc
export terminal="alacritty"
export web_browser="firefox"
export file_manager="pcmanfm"
export editor="emacsclient -c -a emacs"
export editor2="$HOME/.config/scripts/bspwm/nvim.sh"
export EDITOR="vim"

#+END_SRC


** essential startups
Now we load essential programs

- =sxhkd= - hotkey daemon. it manages all keyboard shortcuts
- =polybar-start.sh= - wrapper script for polybar (the panel/bar)
- =wall.sh= - script that sets random wallpaper from set directory
- =picom= - a compositor. With that you can have some effects and transparency in programs (like terminal)
- =dunst= - notification daemon
- =udiskie= is disk drive mouning daemon
- =emacs= daemon is for quicker emacs loading

#+BEGIN_SRC shell
sxhkd &

~/.config/scripts/bspwm/polybar-start.sh

~/.config/scripts/bspwm/wall.sh

picom &

dunst -config ~/.config/dunst/dracula &

udiskie &

emacs --daemon

#+END_SRC

** bspc rules
These are rules and options for bspwm.

With =bspc monitor= you can set amount of workspaces you have

Then we have few mouse settings, window border and gap settings and 3 other things (idk what they do)

Then we have rules.

- idk what =Screenkey= rule does but I was using it at the start of configuring bspwm to see code for keyboard keys
- =emacs= doesn't tile by default so I set it to tile
- =arandr= is little gui for xrandr(setting up displays in xorg) so I keep it as floating
- =zathura= (cool pdf and books reader) as emacs doesn't tile
#+BEGIN_SRC shell
bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config focus_follows_pointer true
bspc config pointer_action1       move
bspc config pointer_action2       resize_side
bspc config pointer_action3       resize_corner

bspc config border_width          3
bspc config window_gap            7

bspc config split_ratio           0.0
bspc config borderless_monocle    true
bspc config gapless_monocle       true

bspc rule -a Screenkey            manage=off

bspc rule -a Emacs                state=tiled
bspc rule -a Arandr               state=floating
bspc rule -a Zathura              state=tiled
#+END_SRC
