#+title: Hyprland configuration
#+PROPERTY: header-args :tangle hyprland.conf
#+auto_tangle: t

=hyprland.conf= is a configuration file for hyprland.
The default path is =$HOME/.config/hypr/hyprland.conf=.

* Table of Contents :toc:
- [[#monitor][Monitor]]
- [[#variables][Variables]]
- [[#startup-programs][Startup programs]]
- [[#input-stuff][Input stuff]]
- [[#animations-and-decorations][Animations and decorations]]
- [[#window-rules][Window rules]]
- [[#keybindings][Keybindings]]

* Monitor
*WARNING*:
This is meant and tested for one display.

#+BEGIN_SRC conf
# See https://wiki.hyprland.org/Configuring/Monitors/
monitor=,preferred,auto,auto

# for verical screen
#normal (no transforms) -> 0
#90 degrees -> 1
#180 degrees -> 2
#270 degrees -> 3
#flipped -> 4
#flipped + 90 degrees -> 5
#flipped + 180 degrees -> 6
#flipped + 270 degrees -> 7
#monitor=,preferred,auto,auto,transform,1

#+END_SRC
* Variables
Here are few variables set:
- terminal
- web browser
- file manager
- first IDE
- second IDE
#+BEGIN_SRC conf
# Source a file (multi-file configs)
# source = ~/.config/hypr/myColors.conf

# Some default env vars.
env = XCURSOR_SIZE,24

# other env vars
$_JAVA_AWT_WM_NONREPARENTING=1
$script = ~/.config/scripts

$terminal = foot
$web_browser = qutebrowser
$file_manager = pcmanfm
$file_manager2 = $terminal -e fish -c "lf"
$editor = emacsclient -c -a ''
# $editor2 = $terminal -e nvim

# For all categories, see https://wiki.hyprland.org/Configuring/Variables/

#+END_SRC
* Startup programs
#+BEGIN_SRC conf
# boot stuff
exec-once = swaync &
# exec-once = udiskie &
exec-once = ~/.local/bin/pyrice &
exec-once = $script/emacs.sh &
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

#+END_SRC
* Input stuff
I'm polish so I use polish keyboard layout.
I also change Caps Lock key to Control key. For a vim or emacs user it's way more convenient.
#+BEGIN_SRC conf
input {
  kb_layout = pl
  # kb_variant =
  # kb_model =
  kb_options = ctrl:nocaps
  # kb_rules =

  follow_mouse = 1

  touchpad {
    natural_scroll = no
    disable_while_typing = no
  }

  sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
}

gestures {
  # See https://wiki.hyprland.org/Configuring/Variables/ for more
  workspace_swipe = on
}

# Example per-device config
# See https://wiki.hyprland.org/Configuring/Keywords/#executing for more
# device:epic-mouse-v1 {
#   sensitivity = -0.5
# }

#+END_SRC
* Animations and decorations
There are also some widow layout options.
#+BEGIN_SRC conf
source = ~/.cache/wal/colors-hyprland.conf

general {
  # See https://wiki.hyprland.org/Configuring/Variables/ for more
  gaps_in = 3
  gaps_out = 10
  border_size = 2
  col.active_border = $color11 45deg
  col.inactive_border = rgba(59595900)

  # layout = master
}

decoration {
  # See https://wiki.hyprland.org/Configuring/Variables/ for more
  col.shadow = rgba(1a1a1aee)

  drop_shadow = no
  shadow_range = 4
  shadow_render_power = 3

  rounding = 5

  blur {
    enabled = yes
    size = 3
    passes = 1
    new_optimizations = on
  }
}

animations {
  enabled = no

  # Some default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more
  bezier = myBezier, 0.05, 0.9, 0.1, 1.05

  animation = windows, 1, 2, myBezier
  # animation = windowsOut, 1, 7, default, popin 80%
  animation = border, 1, 10, default
  animation = borderangle, 1, 8, default
  animation = fade, 1, 2, default
  animation = workspaces, 1, 2, default
}

# dwindle {
#   # See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
#   pseudotile = yes # master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
#   preserve_split = yes # you probably want this
# }

master {
  # See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
  new_is_master = true
  orientation = center
}

misc {
  disable_hyprland_logo = true
  vfr = true                    # lower the amount of sent frames when nothing is happening on-screen
  # background_color = rgb(000000)
}

#+END_SRC
* Window rules
Before window rules there is some mouse config but idk if it does anything (it's probably default)

Then we have window rules and border color for floating windows
#+BEGIN_SRC conf
# Example windowrule v1
# windowrule = float, ^(kitty)$
# Example windowrule v2
# windowrulev2 = float,class:^(kitty)$,title:^(kitty)$
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

windowrule = float, wdisplays
windowrule = float, blueberry
windowrule = float, pavucontrol
windowrule = float, swayimg
windowrule = float, gcolor3
# windowrule = float, org.keepassxc.KeePassXC
windowrule = fullscreen, Waydroid
windowrule = opacity 1.0 override 0.05 override,^(scratch)$
# windowrulev2 = float,class:^(scratch)$
windowrulev2 = float,title:^(Unlock Database - KeePassXC)$
windowrulev2 = float,title:^(KeePassXC - Browser Access Request)$
windowrulev2 = float,class:^(firefox)$,title:^(Picture-in-Picture)$
windowrulev2 = bordercolor rgb(FF5555) rgb(880808),floating:1

#+END_SRC
* Keybindings
Probably the most important thing in here

- Basics
| Keybinding            | command                              |
|-----------------------+--------------------------------------|
| SUPER + T             | launches terminal                    |
| SUPER + W             | launches web browser                 |
| SUPER + E             | launches IDE (emacs)                 |
| SUPER + Alt + E       | launches IDE (emacs) as a scratchpad |
| SUPER + F             | launches file manager (pcmanfm)      |
| SUPER + Shift + F     | launches second file manager (lf)    |
| SUPER + Enter         | launches rofi (app launcher)         |
| SUPER + Tab           | launches rofi in window mode         |
| SUPER + Shift + Enter | launches script hub                  |

- Other stuff
| Keybinding        | command                                     |
|-------------------+---------------------------------------------|
| SUPER + M         | launches task manager                       |
| SUPER + Shift + M | launches task manager with sudo permissions |

- Web scripts
| Keybinding              | command                                    |
|-------------------------+--------------------------------------------|
| SUPER + /               | launches web search                        |
| SUPER + Shift + /       | launches bookmarks menu                    |
| SUPER + Alt + /         | puts item in clipboard into bookmarks file |
| SUPER + Shift + Alt + / | edits bookmarks file directly              |

- Laptop keys
| Keybinding          | command                    |
|---------------------+----------------------------|
| Raise Volume key    | self explenatory           |
| Lower Volume key    | self explanatory           |
| Audio Mute key      | self explanatory           |
| Brightness Up key   | self explanatory           |
| Brightness Down key | self explanatory           |
| PrintScreen         | launches screenshot script |

- Other things
| Keybinding         | command                                                      |
|--------------------+--------------------------------------------------------------|
| SUPER + F2         | launches sound volume changing menu(if you're not on laptop) |
| SUPER + F7         | launches network menu                                        |
| SUPER + Shift + F7 | launches bluetooth menu                                      |
| SUPER + F10        | launches display menu                                        |
| SUPER + F9         | launches drive management menu                               |
| SUPER + Delete     | kills clicked window                                         |

- Desktop management
| Keybinding        | command                                             |
|-------------------+-----------------------------------------------------|
| SUPER + ALT + R   | theme reload (wallpaper change and colorscheme)     |
| SUPER + Q         | closes the window                                   |
| SUPER + Shift + Q | launches power menu                                 |
| SUPER + P         | turns peudo tiling                                  |
| SUPER + down      | (from left/right turns window positions to up/down) |
| SUPER + V         | makes the current window floating                   |
| SUPER + Alt + F   | makes the current window fullscreen                 |
| SUPER + N         | launches notification center                        |

- Window and workspace management
| Keybinding          | command                                                                  |
|---------------------+--------------------------------------------------------------------------|
| SUPER + h/j/k/l     | changes window focus left/down/up/right                                  |
| SUPER + 1-9         | changes to workspace 1-9                                                 |
| SUPER + Shift + 1-9 | moves current window to worskpace 1-9                                    |
| SUPER + Shift + k/j | moves to left or right workspace                                         |
| SUPER + Shift + h/l | moves current window to left/right workspace and moves to that workspace |
| SUPER + LMB         | lets you drag and move windows to different positions                    |
| SUPER + RMB         | lets you resize windows                                                  |
| SUPER + Scroll      | lets you scroll between workspaces                                       |

=$mainMod= is a variable to super (windows) key

#+BEGIN_SRC conf
# See https://wiki.hyprland.org/Configuring/Keywords/ for more
$mainMod = SUPER

# Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more

# basic stuff
bind = $mainMod, T,                exec, $terminal
bind = $mainMod, W,                exec, $web_browser
bind = $mainMod, E,                exec, $editor
bind = $mainMod ALT, E,            exec, $editor -e "(scratch-buffer)"
bind = $mainMod SHIFT, E,          exec, $editor2
bind = $mainMod, F,                exec, $file_manager
bind = $mainMod SHIFT, F,          exec, $file_manager2
bind = $mainMod, Return,           exec, rofi -show drun
# bind = $mainMod, Tab,              exec, rofi -show window

# script hub
bind = $mainMod SHIFT, Return,     exec, $script/hub.sh

# other
bind = $mainMod, M,                exec, $terminal -e htop
bind = $mainMod SHIFT, M,          exec, $terminal -e sudo htop

# theme change
bind = $mainMod ALT, R,            exec, ~/.local/bin/pyrice

# web stuff
bind = $mainMod, 61,               exec, $script/web-search.sh
bind = $mainMod SHIFT, 61,         exec, $script/bookmarks.sh
bind = $mainMod ALT, 61,           exec, $script/bookmarking.sh
bind = $mainMod ALT SHIFT, 61,     exec, emacsclient -c -a 'nvim' ~/Sync/foo/wazne/bookmarks

# laptop keys
binde = ,XF86AudioRaiseVolume,     exec, pactl set-sink-volume @DEFAULT_SINK@ +5%
binde = ,XF86AudioLowerVolume,     exec, pactl set-sink-volume @DEFAULT_SINK@ -5%
bind = ,XF86AudioMute,             exec, pactl set-sink-mute @DEFAULT_SINK@ toggle

bind = ,XF86MonBrightnessUp,       exec, light -A 3
bind = ,XF86MonBrightnessDown,     exec, light -U 3

bind = ,Print,                     exec, $script/hypr/screenshot.sh

bind = $mainMod, F2,               exec, $script/volume.sh
bind = $mainMod, F7,               exec, networkmanager_dmenu
bind = $mainMod SHIFT, F7,         exec, rofi-bluetooth
bind = $mainMod, F10,              exec, wdisplays
bind = $mainMod, F9,               exec, $script/udiskie-unmount.sh
bind = $mainMod, Delete,           exec, hyprctl kill

# changing theme
bind = $mainMod, F6,               exec, $script/themes/main.sh

#bind = $mainMod, X,                exit,
bind = $mainMod, Q,                killactive,
bind = $mainMod SHIFT, Q,          exec, $script/power.sh

bind = $mainMod, P,                pseudo, # dwindle
bind = $mainMod, down,             togglesplit, # dwindle
bind = $mainMod, V,                togglefloating,
bind = $mainMod ALT, F,            fullscreen
bind = $mainMod, N,                exec, swaync-client -t


# Move focus
bind = $mainMod, h, movefocus, l
bind = $mainMod, j, movefocus, d
bind = $mainMod, k, movefocus, u
bind = $mainMod, l, movefocus, r

# Switch workspaces with mainMod + [0-9]
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

# Move active window to a workspace
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9
bind = $mainMod SHIFT, 0, movetoworkspace, 10

bind = $mainMod SHIFT, j, workspace, +1
bind = $mainMod SHIFT, k,  workspace, -1

# Move active window to a next or previous workspace
bind = $mainMod SHIFT, h,  movetoworkspace, -1
bind = $mainMod SHIFT, l, movetoworkspace, +1

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

# Scroll through existing workspaces with mainMod + scroll
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1

# trying submaps to act as keychords
bind = $mainMod, r, submap, reload/reset
submap = reload/reset
bind = ,w,exec,$script/hypr/waybar-start.sh
bind = ,w,submap,reset
bind = ,e,exec,$script/emacs.sh
bind = ,e,submap,reset
bind=,escape,submap,reset
submap = reset

bind = $mainMod, S, movetoworkspace, special # moves window to scratch workspace
bind = $mainMod SHIFT, S, togglespecialworkspace # toggle scratch workspace on/off

bindl=,switch:Lid Switch,exec,~/.cache/wal/swaylock.sh # hyprctl devices to see lid name etc.

# will switch to a submap called resize
bind=$mainMod SHIFT ,R,submap,resize

submap=resize

# sets repeatable binds for resizing the active window
binde=,right,resizeactive,10 0
binde=,left,resizeactive,-10 0
binde=,up,resizeactive,0 -10
binde=,down,resizeactive,0 10

# use reset to go back to the global submap
bind=,escape,submap,reset

# will reset the submap, meaning end the current one and return to the global one
submap=reset
#+END_SRC
