#+TITLE: Arch Linux rice install
#+PROPERTY: header-args :tangle install.sh
#+auto_tangle: t
I decided to put all installation shell scripts in this file because it's cool.
The script generated from this is called ~install.sh~.

* WARNING
To anyone that wants to apply these dotfiles.
The script is intended to use after minimal Arch Linux has been installed.
The script assumes that you have network connection you use *systemd*.

* Services
** Bluetooth
#+begin_src sh :shebang "#!/usr/bin/env bash"
sudo pacman -S --noconfirm bluez
sudo systemctl enable bluetooth
#+end_src
** Pipewire
The issue with this is that 
I think pipewire sets up its' service automatically with reboot.
#+begin_src sh
sudo pacman -Rc --noconfirm pulseaudio pulseaudio-alsa pulseaudio-bluetooth
sudo pacman -S --noconfirm pipewire pipewire-pulse pipewire-audio
#+end_src

** Display manager (SDDM)
#+begin_src sh
sudo pacman -S --noconfirm sddm qt5-quickcontrols qt5-quickcontrols2 qt5-graphicaleffects
sudo systemctl enable sddm
git clone https://github.com/AudacityXD62/win7welcomesddm.git
sudo mv win7welcomesddm /usr/share/sddm/themes/

sddm_file_path="/usr/lib/sddm/sddm.conf.d/default.conf"

old_line=$(grep "Current=" $sddm_file_path)

# Check if the old line exists in the file
if [ -n "$old_line" ]; then
  # Replace the line using sed
  new_line='Current=win7welcomesddm'
  sudo sed -i "s|$old_line|$new_line|" "$sddm_file_path"
  echo "SDDM theme applied successfully!"
else
  echo "SDDM theme not applied successfully!"
fi
#+end_src
* Arco Linux pacman repo
Some packages installed below are from Arco Linux's repo because I don't want to install everything from AUR.
#+begin_src sh
repo_lines="
[arcolinux_repo_3party]
SigLevel = Required TrustAll
Server = https://arcolinux.github.io/arcolinux_repo_3party/\$arch"

# Backup the original pacman.conf file
sudo cp /etc/pacman.conf /etc/pacman.conf.bak

# Add the repository lines to the end of pacman.conf
sudo bash -c "echo '$repo_lines' >> /etc/pacman.conf"

sudo pacman -Syyu
#+end_src

* Dependencies
** Normal dependiencies
#+BEGIN_SRC sh
sudo pacman -S --noconfirm hyprland \
      	                   htop \
                           papirus-icon-theme \
                           waybar \
                           eza \
                           qt5-wayland \
                           swaybg \
                           blueberry \
                           mako \
                           swaync \
                           wdisplays-git \
                           wl-clipboard \
                           grim \
                           slurp \
                           bat-extras \
                           fish \
                           starship \
                           pcmanfm-gtk3 \
                           file-roller \
                           p7zip \
                           unrar \
                           zathura \
			   zathura-pdf-mupdf \
                           neovim \
                           gammastep \
                           lolcat \
                           otf-codenewroman-nerd \
                           ttf-ubuntu-nerd \
                           ttf-go-nerd \
                           ttf-jetbrains-mono-nerd \
                           noto-fonts-emoji \
                           pavucontrol \
                           qt5ct \
                           foot \
                           networkmanager \
                           gksu \
                           qutebrowser \
                           mpv \
                           polkit-gnome \
                           grimshot \
                           dracula-cursors-git \
                           light \
                           chafa \
                           ripgrep \
                           fzf \
                           hyprpicker-git \
                           swayimg \
                           emacs \
                           lf \
                           stow \
                           expac \
			   python-tldextract \
                           python-pynacl \
		           fastfetch \
                           git \
                           tree-sitter
#+end_src

** Yay dependencies
yay is AUR wrapper which is can also be used as frontend to pacman.
#+begin_src sh
if $(pacman -Q yay >> /dev/null); then
  echo "yay is installed"
else
  git clone https://aur.archlinux.org/yay-bin
  cd yay-bin
  makepkg -si --noconfirm
  cd ..
  rm -rf yay-bin/
fi
#+end_src

Now we install some packages with yay
#+begin_src sh
yay -S --noconfirm networkmanager-dmenu-git \
                   clipboard \
                   rofi-bluetooth-git \
                   ctpv-git \
                   cp-p-git \
                   rofi-lbonn-wayland-git \
                   pokemonsay-newgenerations-git \
                   fortune-mod-vimtips \
                   # krabby-bin \
                   # dracula-gtk-theme
                   # catppuccin-gtk-theme-mocha
                   # catppuccin-gtk-theme-latte
                   # bitwarden-rofi-git \
                   # udiskie-dmenu-git
#+end_src

** Pywal dependencies
Pywal is like Material You from android but on Linux
#+begin_src sh
yay -S --noconfirm pywal \
                   python-inotify-simple \
                   python-psutil \
                   python-prctl \
                   python-daemon \
                   wpgtk \
                   gtk-theme-flat-color-git

wpg-install.sh -g
#+end_src

* Optional software
#+begin_src sh
yay -S --noconfirm appimagelauncher-bin \
                   keepassxc \
                   syncthing
                   # syncthing-gtk
#+end_src
* Touchpad setup on Xorg
#+begin_src sh
touchpad_conf='Section "InputClass"
        Identifier "touchpad"
        MatchIsTouchpad "on"
        Driver "libinput"
        Option "Tapping" "on"
        Option "TappingButtonMap" "lrm"
        Option "NaturalScrolling" "off"
        Option "ScrollMethod" "twofinger"
EndSection'

if [ -e "/etc/X11/xorg.conf.d/90-touchpad.conf" ]; then
  echo "It seems you already have touchpad configuration. No changes have been made."
  exit
else
  sudo mkdir -p /etc/X11/xorg.conf.d
  sudo touch /etc/X11/xorg.conf.d/90-touchpad.conf
  echo "$touchpad_conf" | sudo tee /etc/X11/xorg.conf.d/90-touchpad.conf > /dev/null
  echo "The changes have been applied. After reboot touchpad should work."
fi
#+end_src
* Latex working in Emacs
Org mode supports latex displaying but that requires some setup.
#+begin_src sh
sudo pacman -S --noconfirm texlive-bin texlive-binextra texlive-latexrecommended texlive-latexextra texlive-plaingeneric
sudo texconfig rehash
texhash
#+end_src
* GRUB theme
#+begin_src sh
git clone https://gitlab.com/imnotpua/grub_gtg

cd grub_gtg

echo "YOU NEED TO TYPE FONT SIZE AND THEME DIRECTORY"
sudo bash ./install.sh

cd ../
rm -rf grub_gtg
#+end_src

* Setting defaults
It sets some apps to be defaults for some files
#+begin_src sh
xdg-mime default org.pwmt.zathura.desktop application/pdf
xdg-settings set default-web-browser org.qutebrowser.qutebrowser.desktop
#+end_src
