#!/bin/sh

pgrep -x sxhkd > /dev/null

# variables for sxhkdrc
export terminal="alacritty"
export launcher="rofi"
export web_browser="firefox"
export file_manager="thunar"

sxhkd &

# script starting polybar
~/.config/polybar/start.sh

# restoring wallpaper
nitrogen --restore

# compositor
compton &

# you can add as many workspaces as you want
bspc monitor -d 1 2 3 4 5 6

bspc config focus_follows_pointer true
bspc config pointer_action1       move
bspc config pointer_action2       resize_side
bspc config pointer_action3       resize_corner
bspc config border_width          3
bspc config window_gap            10

bspc config split_ratio           0.0
bspc config borderless_monocle    true
bspc config gapless_monocle       true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=on
