#!/usr/bin/env bash
# variables for sxhkdrc
export terminal="alacritty"
export web_browser="firefox"
export file_manager="pcmanfm"
export editor="emacs"
export editor2="$HOME/.config/scripts/bspwm/nvim.sh"
export EDITOR="vim"

sxhkd &

~/.config/scripts/bspwm/polybar-start.sh

~/.config/scripts/bspwm/wall.sh

picom &

dunst -config ~/.config/dunst/dracula &

/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config focus_follows_pointer true
bspc config pointer_action1       move
bspc config pointer_action2       resize_side
bspc config pointer_action3       resize_corner

bspc config border_width          3
bspc config window_gap            7

bspc config split_ratio           0.0
bspc config borderless_monocle    true
bspc config gapless_monocle       true

bspc rule -a Screenkey            manage=off

bspc rule -a Emacs                state=tiled
bspc rule -a Zathura              state=tiled
bspc rule -a Arandr               state=floating
