#+title: Hyprland configuration
#+PROPERTY: header-args :tangle hyprland.conf
#+auto_tangle: t

* Table of Contents :toc:
- [[#beginning][beginning]]
- [[#code][code]]
  - [[#monitor][monitor]]
  - [[#startup-programs][startup programs]]
  - [[#variables][variables]]
  - [[#input-stuff][input stuff]]
  - [[#animations-and-decorations][animations and decorations]]
  - [[#window-rules][window rules]]
  - [[#keybindings][keybindings]]

* beginning
=hyprland.conf= is a configuration file for hyprland.
The default path is =$HOME/.config/hypr/hyprland.conf=.

* code

** monitor
*WARNING*:
This is meant and tested for one display.

#+BEGIN_SRC conf
# See https://wiki.hyprland.org/Configuring/Monitors/
monitor=,preferred,auto,auto

# for verical screen
#normal (no transforms) -> 0
#90 degrees -> 1
#180 degrees -> 2
#270 degrees -> 3
#flipped -> 4
#flipped + 90 degrees -> 5
#flipped + 180 degrees -> 6
#flipped + 270 degrees -> 7
#monitor=,preferred,auto,auto,transform,1

#+END_SRC

** startup programs
Here are started:
- waybar (panel/bar)
- dunst (notification daemon)
- script for setting wallpaper
- script for setting gtk themes
- gnome polkit (thing for authentication)
- emacs daemon
#+BEGIN_SRC conf
# boot stuff
exec-once = ~/.config/scripts/hypr/waybar-start.sh
exec-once = ~/.config/scripts/hypr/wall.sh
exec-once = ~/.config/scripts/hypr/theme.sh
exec-once = dunst -config ~/.config/dunst/dracula &
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = emacs --daemon

#+END_SRC

** variables
Here are few variables set:
- terminal
- web browser
- file manager
- first IDE
- second IDE

#+BEGIN_SRC conf
# Source a file (multi-file configs)
# source = ~/.config/hypr/myColors.conf

# Some default env vars.
env = XCURSOR_SIZE,24


# other env vars
$_JAVA_AWT_WM_NONREPARENTING=1

$terminal=foot
$web_browser=firefox
$file_manager=pcmanfm
$editor=emacsclient -c -a 'emacs'
$editor2=$terminal -e nvim

# For all categories, see https://wiki.hyprland.org/Configuring/Variables/

#+END_SRC

** input stuff
I'm polish so I use polish keyboard layout.
#+BEGIN_SRC conf
input {
    kb_layout = pl
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1

    touchpad {
        natural_scroll = no
    }

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
}

gestures {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more
    workspace_swipe = on
}

#+END_SRC

** animations and decorations
There are also some widow layout options.

#+BEGIN_SRC conf
general {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more

    gaps_in = 3
    gaps_out = 10
    border_size = 2
    col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
    col.inactive_border = rgba(595959aa)

    layout = dwindle
}

decoration {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more

    rounding = 5
    blur = yes
    blur_size = 3
    blur_passes = 1
    blur_new_optimizations = on

    drop_shadow = yes
    shadow_range = 4
    shadow_render_power = 3
    col.shadow = rgba(1a1a1aee)
}

animations {
    enabled = yes

    # Some default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more

    bezier = myBezier, 0.05, 0.9, 0.1, 1.05

    animation = windows, 1, 7, myBezier
    animation = windowsOut, 1, 7, default, popin 80%
    animation = border, 1, 10, default
    animation = borderangle, 1, 8, default
    animation = fade, 1, 5, default
    animation = workspaces, 1, 6, default
}

dwindle {
    # See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
    pseudotile = yes # master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = yes # you probably want this
}

master {
    # See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
    new_is_master = true
}

#+END_SRC

** window rules
Before window rules there is some mouse config but idk if it does anything (it's probably default)

Then we have window rules
- wdisplays is a program for managing displays on wayland
- feh is a image viewer
- waydroid is an android container so it's better to have it in fullscreen
- picture in picture mode in firefox
- border color for floating windows
#+BEGIN_SRC conf
# Example per-device config
# See https://wiki.hyprland.org/Configuring/Keywords/#executing for more
device:epic-mouse-v1 {
    sensitivity = -0.5
}

# Example windowrule v1
# windowrule = float, ^(kitty)$
# Example windowrule v2
# windowrulev2 = float,class:^(kitty)$,title:^(kitty)$
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

windowrule = float, wdisplays
windowrule = float, feh
windowrule = fullscreen, Waydroid
windowrulev2 = float,class:^(firefox)$,title:^(Picture-in-Picture)$
windowrulev2 = bordercolor rgb(FF5555) rgb(880808),floating:1

#+END_SRC

** keybindings
Probably the most important thing in here

| Keybinding              | command                                                                     |
|-------------------------+-----------------------------------------------------------------------------|
| SUPER + T               | launches terminal                                                           |
| SUPER + W               | lunches web browser                                                         |
| SUPER + E               | launches first IDE                                                          |
| SUPER + Shift + E       | launches second IDE                                                         |
| SUPER + F               | launches file manager                                                       |
| SUPER + Enter           | launches rofi (app launcher)                                                |
| SUPER + Shift + Enter   | launches script hub                                                         |
| SUPER + B               | launches bitwarden menu                                                     |
| SUPER + M               | launches task manager                                                       |
| SUPER + Shift + M       | launches task manager with admin permissions                                |
| SUPER + /               | launches web search                                                         |
| SUPER + Shift + /       | launches bookmarks menu                                                     |
| SUPER + Alt + /         | puts item in clipboard into bookmarks file                                  |
| SUPER + Shift + Alt + / | edits bookmarks file directly                                               |
| Raise Volume key        | self explenatory                                                            |
| Lower Volume key        | self explanatory                                                            |
| Audio Mute key          | self explanatory                                                            |
| Brightness Up key       | self explanatory                                                            |
| Brightness Down key     | self explanatory                                                            |
| PrintScreen             | launches screenshot script                                                  |
| SUPER + F2              | launches sound volume changing menu(if you're not on laptop)                |
| SUPER + F7              | launches network menu                                                       |
| SUPER + Shift + F7      | launches bluetooth menu                                                     |
| SUPER + F10             | launches display menu                                                       |
| SUPER + F9              | launches drive management menu                                              |
| SUPER + F6              | launches theme changing menu                                                |
| SUPER + Q               | closes the window                                                           |
| SUPER + Shift + Q       | launches power menu                                                         |
| SUPER + P               | turns peudo tiling                                                          |
| SUPER + J               | (from left/right turns window positions to up/down)                         |
| SUPER + V               | makes the current window floating                                           |
| SUPER + Shift + F       | makes the current window fullscreen                                         |
| SUPER + ←/↓/→/↑         | changes window focus according to arrow key                                 |
| SUPER + 1-9             | changes to workspace 1-9                                                    |
| SUPER + Shift + 1-9     | moves current window to worskpace 1-9                                       |
| SUPER + Ctrl + ←/→      | moves to left or right workspace                                            |
| SUPER + Shift + ←/→     | moves current window to left or right workspace and moves to that workspace |
| SUPER + LMB             | lets you drag and move windows to different positions                       |
| SUPER + RMB             | lets you resize windows                                                     |
| SUPER + Scroll          | lets you scroll between workspaces                                          |

=$mainMod= is a variable to super(windows) key

#+BEGIN_SRC conf
# See https://wiki.hyprland.org/Configuring/Keywords/ for more
$mainMod = SUPER


# Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more

# basic stuff
bind = $mainMod, T,                exec, $terminal
bind = $mainMod, W,                exec, $web_browser
bind = $mainMod, E,                exec, $editor
bind = $mainMod SHIFT, E,          exec, $editor2
bind = $mainMod, F,                exec, $file_manager
bind = $mainMod, Return,           exec, rofi -show drun -config ~/.config/rofi/config.rasi

# script hub
bind = $mainMod SHIFT, Return,     exec, ~/.config/scripts/hub.sh

# other
bind = $mainMod, B,                exec, bwmenu
bind = $mainMod, M,                exec, $terminal -e htop
bind = $mainMod SHIFT, M,          exec, $terminal -e sudo htop


# web stuff
bind = $mainMod, 61,               exec, ~/.config/scripts/web-search.sh
bind = $mainMod SHIFT, 61,         exec, ~/.config/scripts/bookmarks.sh
bind = $mainMod ALT, 61,           exec, ~/.config/scripts/bookmarking.sh
bind = $mainMod ALT SHIFT, 61,     exec, $terminal -e nvim ~/Documents/bookmarks

# laptop keys
bind = ,XF86AudioRaiseVolume,      exec, pactl set-sink-volume @DEFAULT_SINK@ +5%
bind = ,XF86AudioLowerVolume,      exec, pactl set-sink-volume @DEFAULT_SINK@ -5%
bind = ,XF86AudioMute,             exec, pactl set-sink-mute @DEFAULT_SINK@ toggle

bind = ,XF86MonBrightnessUp,       exec, enlighten +3%
bind = ,XF86MonBrightnessDown,     exec, enlighten -3%

bind = ,Print,                     exec, ~/.config/scripts/hypr/screenshot.sh

bind = $mainMod, F2,               exec, ~/.config/scripts/volume.sh
bind = $mainMod, F7,               exec, networkmanager_dmenu
bind = $mainMod SHIFT, F7,         exec, rofi-bluetooth
bind = $mainMod, F10,              exec, wdisplays
bind = $mainMod, F9,               exec, udiskie-dmenu

# changing theme
bind = $mainMod, F6,               exec, ~/.config/scripts/themes/main.sh

#bind = $mainMod, X,                exit,
bind = $mainMod, Q,                killactive,
bind = $mainMod SHIFT, Q,          exec, ~/.config/scripts/power.sh

bind = $mainMod, P,                pseudo, # dwindle
bind = $mainMod, J,                togglesplit, # dwindle
bind = $mainMod, V,                togglefloating,
bind = $mainMod SHIFT, f,          fullscreen


# Move focus
bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d

# Switch workspaces with mainMod + [0-9]
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9
bind = $mainMod SHIFT, 0, movetoworkspace, 10


# Scroll through workspaces with mainMod + scroll
bind = $mainMod CTRL, right, workspace, +1
bind = $mainMod CTRL, left,  workspace, -1

# Move active window to a next or previous workspace with mainMod + SHIFT + [ ->,<- ]
bind = $mainMod SHIFT, left,  movetoworkspace, -1
bind = $mainMod SHIFT, right, movetoworkspace, +1

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

# Scroll through existing workspaces with mainMod + scroll
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1
#+END_SRC
